name: Setup Reviewdog
runs:
  using: "composite"
  steps:
    - name: Setup reviewdog/rubocop
      uses: reviewdog/action-rubocop@v2
      with:
        rubocop_version: gemfile
        rubocop_extensions: rubocop-rails:gemfile rubocop-rspec:gemfile
        reporter: github-pr-review
    - name: Setup reviewdog/brakeman
      uses: reviewdog/action-brakeman@v2
      with:
        brakeman_version: 4.8.2
        reporter: github-pr-review
